### ISSUE TITLE
Data corruption

### ISSUE THREAD

**Issue by ghost** [abronan/proton#1]
With a single node running for a long period of time, data becomes corrupt.  Note how eventually extra characters get appeneded to both the keyname and the value name over time.

```
$ ./proton init
raft2016/01/28 16:52:32 INFO: cbf29ce484222325 became follower at term 0
raft2016/01/28 16:52:32 INFO: newRaft cbf29ce484222325 [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]

[...]

ykey
     = myvalue

mykey = myvalue
mykeyR = myvalueR
mykeyS = myvalueS
mykeyy = myvaluey
mykey = myvalue
mykeyL = myvalueL
mykeyU = myvalueU
mykey@ = myvalue@
mykeyQ = myvalueQ
mykeyB = myvalueB
mykey8 = myvalue8
mykeyu = myvalueu

mykey9 = myvalue9
mykeyI = myvalueI
mykeyT = myvalueT
myke = myvalue
mykey    = myvalue  
 = myvalue
mykey = myvalue
mykey+ = myvalue+
mykey = myvalue
mykey = myvalue

```

**Comment by abronan** [comment]
Thanks @mgoelzer, yeah it's just bad string encoding with the cli example that was just for testing the simple comm layer. I'll soon encode keys and values through **protobuf** instead, this will get rid of it.

**Comment by ghost** [comment]
Awesome, just wanted to make sure you were aware
